#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-probed
Version  : 0.0.7
Release  : 2
URL      : https://files.pythonhosted.org/packages/03/d6/81c7918c83ff21ed65ae59d25bab31ec9755272a2c55182140999dbc7ef8/probed-0.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/03/d6/81c7918c83ff21ed65ae59d25bab31ec9755272a2c55182140999dbc7ef8/probed-0.0.7.tar.gz
Summary  : Probed collection
Group    : Development/Tools
License  : MIT
Requires: pypi-probed-bin = %{version}-%{release}
Requires: pypi-probed-license = %{version}-%{release}
Requires: pypi-probed-python = %{version}-%{release}
Requires: pypi-probed-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
# Probed collections
This project is part of the [Pyrustic Ecosystem](https://pyrustic.github.io).

%package bin
Summary: bin components for the pypi-probed package.
Group: Binaries
Requires: pypi-probed-license = %{version}-%{release}

%description bin
bin components for the pypi-probed package.


%package license
Summary: license components for the pypi-probed package.
Group: Default

%description license
license components for the pypi-probed package.


%package python
Summary: python components for the pypi-probed package.
Group: Default
Requires: pypi-probed-python3 = %{version}-%{release}

%description python
python components for the pypi-probed package.


%package python3
Summary: python3 components for the pypi-probed package.
Group: Default
Requires: python3-core
Provides: pypi(probed)

%description python3
python3 components for the pypi-probed package.


%prep
%setup -q -n probed-0.0.7
cd %{_builddir}/probed-0.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639073000
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-probed
cp %{_builddir}/probed-0.0.7/LICENSE %{buildroot}/usr/share/package-licenses/pypi-probed/f733bb36945a3e57dbdcc2d53cb548682d6c0d57
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}*/usr/lib/python3.*/site-packages/tests/__init__.py
rm -f %{buildroot}*/usr/lib/python3.*/site-packages/tests/__pycache__/__init__.cpython-*.pyc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/probed

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-probed/f733bb36945a3e57dbdcc2d53cb548682d6c0d57

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
